import {
  Addition,
  ClimaticEnvironmental,
  DefinedIndicator,
  EnvironmentalEngineer,
  Goal,
  InformationAboutSelection,
  LabId,
  Method,
  NormativeDocument,
  ObjectName,
  PassedSample,
  Place,
  Planning,
  Preparation,
  Representative,
  Sample,
  SampleType,
  ToolType,
  TypeOfSample,
} from '@app/models';

export const Entities = [
  Addition,
  ClimaticEnvironmental,
  DefinedIndicator,
  LabId,
  EnvironmentalEngineer,
  Goal,
  InformationAboutSelection,
  Method,
  NormativeDocument,
  ObjectName,
  PassedSample,
  Place,
  Planning,
  Preparation,
  Representative,
  SampleType,
  Sample,
  ToolType,
  TypeOfSample,
];
