export enum TypeKey {
  CUSTOMER = 'customer',
  GENERAL_CUSTOMER = 'generalCustomer',
  LAB = 'lab',
  TYPE_OF_SAMPLE = 'typeOfSample',
  PLACE = 'place',
  METHOD = 'method',
  TOOL_TYPE = 'toolType',
  NORMATIVE_DOCUMENT = 'normativeDocument',
  SAMPLE_TYPE = 'sampleType',
  PREPARATION = 'preparation',
  GOAL = 'goal',
  DEFINED_INDICATORS = 'definedIndicators',
  ENVIRONMENTAL_ENGINEER = 'environmentalEngineer',
  REPRESENTATIVE = 'representative',
  PASSED_SAMPLE = 'passedSample',
  APPLICATION = 'application',
}
