import {
  AdditionAct,
  ClimaticEnvironmentalAct,
  CustomerAct,
  DefinedIndicatorAct,
  EnvironmentalEngineerAct,
  GeneralCustomerAct,
  GoalAct,
  InformationAboutSelectionAct,
  LabAct,
  MethodAct,
  NormativeDocumentAct,
  ObjectNameAct,
  PassedSampleAct,
  PlaceAct,
  PlanningAct,
  PreparationAct,
  RepresentativeAct,
  SampleAct,
  SampleTypeAct,
  ToolTypeAct,
  TypeOfSampleAct,
} from '@app/models';

export const ConsumersEntities = [
  CustomerAct,
  GeneralCustomerAct,
  LabAct,
  TypeOfSampleAct,
  ObjectNameAct,
  PlaceAct,
  MethodAct,
  ToolTypeAct,
  ClimaticEnvironmentalAct,
  PlanningAct,
  NormativeDocumentAct,
  SampleTypeAct,
  SampleAct,
  PreparationAct,
  GoalAct,
  //   DefinedIndicatorAct,
  AdditionAct,
  InformationAboutSelectionAct,
  EnvironmentalEngineerAct,
  RepresentativeAct,
  PassedSampleAct,
];
