import {
  Customer,
  EnvironmentalEngineer,
  DefinedIndicator,
  GeneralCustomer,
  Goal,
  Lab,
  Method,
  NormativeDocument,
  PassedSample,
  Place,
  Preparation,
  Representative,
  SampleType,
  ToolType,
  TypeOfSample,
} from '@app/models';

export const ConsumersEntities = [
  Customer,
  GeneralCustomer,
  Lab,
  TypeOfSample,
  Place,
  Method,
  ToolType,
  NormativeDocument,
  SampleType,
  Preparation,
  Goal,
  DefinedIndicator,
  EnvironmentalEngineer,
  Representative,
  PassedSample,
];
