export enum CONSUMERS {
  CUSTOMER = 'Cusomer',
  GENERAL_CUSTOMER = 'GeneralCustomer',
  LAB = 'Lab',
  TYPE_OF_SAMPLE = 'TypeOfSample',
  OBJECT_NAME = 'ObjectName',
  PLACE = 'Place',
  METHOD = 'Method',
  TOOL_TYPE = 'ToolType',
  CLIMATIC_ENVIRONMENTAL = 'CLIMATIC_ENVIRONMENTAL',
  PLANNING = 'Planning',
  NORMATIVE_DOCUMENT = 'NormativeDocument',
  SAMPLE_TYPE = 'SampleType',
  SAMPLE = 'Sample',
  PREPARATION = 'Preparation',
  GOAL = 'Goal',
  DEFINED_INDICATORS = 'DefinedIndicator',
  ADDITIONS = 'ADDITIONS',
  INFORMATION_ABOUT_SELECTION = 'InformationAboutSelection',
  ENVIRONMENTAL_ENGINEER = 'EnvironmentalEngineer',
  REPRESENTATIVE = 'Representative',
  PASSED_SAMPLE = 'PassedSample',
}
